variable "env" {}
variable "component" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "lb_dns_name" {}
variable "subnets" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "instance_type" {}
variable "allow_ssh_cidr" {}
variable "sg_subnet_cidr" {}
variable "app_port" {}
variable "listener_arn" {}
variable "lb_rule_priority" {}
